# ======================
# DATABASE (PostgreSQL)
# ======================
spring.datasource.url=jdbc:postgresql://localhost:5432/workforce_db
spring.datasource.username=bryantferguson
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver

# ======================
# JPA / HIBERNATE
# ======================
spring.jpa.database=postgresql

spring.jpa.hibernate.ddl-auto=update

# ======================
# DEBUGGING (DEV ONLY)
# ======================
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Optional but helpful (prevents SQL errors on startup)
spring.jpa.open-in-view=false

# ======================
# OPENAI API KEY
openai.api.key=${OPENAI_API_KEY}
adzuna.app.id=${ADZUNA_APP_ID}
adzuna.app.key=${ADZUNA_APP_KEY}

logging.level.org.springframework.jdbc=DEBUG
logging.level.org.hibernate.engine.jdbc.env.internal=DEBUG

logging.level.com.zaxxer.hikari=DEBUG
logging.level.org.springframework.boot.autoconfigure.jdbc=DEBUG
logging.level.org.hibernate.SQL=DEBUG

